package com.sample
 
import com.sample.DroolsTest.Message;
import com.sample.GUI;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

declare Question
  quest : String
  answers : String
end

declare GUI_state
  currentQuestion : String = "Are you ready to start?"
  possible: String = ""
  ans : String = ""
  img : String = ""
end
rule "Initialization"
when
	ui : GUI()
then
	
	GUI_state state = new GUI_state();
	insert(state);
	Question q = new Question("Are you in Scotland?", "Yes;No");
  	insert(q);
  	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "scotland-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Are you in Scotland?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Do you sleep in a double-wide?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "scotland-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Are you in Scotland?",ans == "Yes")
	ui: GUI()
then
	System.out.println("brew dog");
	state.setImg("src/main/resources/grafiki/brewdog.png");
	ui.closeGUI(state.getImg());
end

rule "doublewide-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Do you sleep in a double-wide?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Are you Bob or Doug McKenzie?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "doublewide-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Do you sleep in a double-wide?",ans == "Yes")
	ui: GUI()
then
	System.out.println("country club");
	state.setImg("src/main/resources/grafiki/countryclubmaltliquor.png");
	ui.closeGUI(state.getImg());
end

rule "doug-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Are you Bob or Doug McKenzie?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Do you live in projects?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "doug-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Are you Bob or Doug McKenzie?",ans == "Yes")
	ui: GUI()
then
	System.out.println("elsinore");
	state.setImg("src/main/resources/grafiki/elsinore.png");
	ui.closeGUI(state.getImg());
end

rule "projects-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Do you live in projects?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Are you a hockey fan eh?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "projects-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Do you live in projects?",ans == "Yes")
	ui: GUI()
then
	System.out.println("colt steel");
	state.setImg("src/main/resources/grafiki/steelreserve.png;src/main/resources/grafiki/colt45.png");
	ui.closeGUI(state.getImg());
end

rule "hockey-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Are you a hockey fan eh?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Do you know how to access the Stargate?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "hockey-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Are you a hockey fan eh?",ans == "Yes")
	ui: GUI()
then
	System.out.println("molson labalt");
	state.setImg("src/main/resources/grafiki/molson.png;src/main/resources/grafiki/labattblue.png");
	ui.closeGUI(state.getImg());
end

rule "stargate-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Do you know how to access the Stargate?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Are you doing that \"ironic\" hipster thing?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "stargate-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Do you know how to access the Stargate?",ans == "Yes")
	ui: GUI()
then
	System.out.println("rheingold esslingers");
	state.setImg("src/main/resources/grafiki/rheingold.png;src/main/resources/grafiki/esslingers.png");
	ui.closeGUI(state.getImg());
end

rule "hipster-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Are you doing that \"ironic\" hipster thing?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Are you the designated driver?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "hipster-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Are you doing that \"ironic\" hipster thing?",ans == "Yes")
	ui: GUI()
then
	System.out.println("pabst");
	state.setImg("src/main/resources/grafiki/pabstblueribbon.png");
	ui.closeGUI(state.getImg());
end

rule "driver-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Are you the designated driver?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Are you at a tailgate or frat party?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "driver-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Are you the designated driver?",ans == "Yes")
	ui: GUI()
then
	System.out.println("odouls");
	state.setImg("src/main/resources/grafiki/odouls.png");
	ui.closeGUI(state.getImg());
end

rule "tailgate-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Are you at a tailgate or frat party?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Is Guinness on tap?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "tailgate-yes" //if answer was yes and question is next
when
	state: GUI_state(currentQuestion=="Are you at a tailgate or frat party?", ans=="Yes");
	ui: GUI();
then
	Question q = new Question("Is your wife nagging you about the beer gut?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "beergut-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Is your wife nagging you about the beer gut?",ans == "Yes")
	ui: GUI()
then
	System.out.println("amstel miller coors budlight");
	state.setImg("src/main/resources/grafiki/amstellight.png;src/main/resources/grafiki/millerlite.png;src/main/resources/grafiki/coorslight.png;src/main/resources/grafiki/budlight.png");
	ui.closeGUI(state.getImg());
end

rule "beergut-image-no" //if answer was no and image is next
when
	state: GUI_state(currentQuestion=="Is your wife nagging you about the beer gut?",ans == "No")
	ui: GUI()
then
	System.out.println("amstel miller coors budweiser moose");
	state.setImg("src/main/resources/grafiki/amstelbeer.png;src/main/resources/grafiki/millerhighlife.png;src/main/resources/grafiki/coors.png;src/main/resources/grafiki/budweiser.png;src/main/resources/grafiki/mooselightlime.png");
	ui.closeGUI(state.getImg());
end

rule "guinness-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Is Guinness on tap?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Is it summer?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "guinness-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Is Guinness on tap?",ans == "Yes")
	ui: GUI()
then
	System.out.println("guinness");
	state.setImg("src/main/resources/grafiki/guinness.png");
	ui.closeGUI(state.getImg());
end

rule "summer-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Is it summer?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Can you speak fluent French, in Russian?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "summer-yes" //if answer was yes and question is next
when
	state: GUI_state(currentQuestion=="Is it summer?", ans=="Yes");
	ui: GUI();
then
	Question q = new Question("Are you paying in change?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "change-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Are you paying in change?",ans == "Yes")
	ui: GUI()
then
	System.out.println("tequiza modelo");
	state.setImg("src/main/resources/grafiki/tequiza.png;src/main/resources/grafiki/modelospecial.png");
	ui.closeGUI(state.getImg());
end

rule "change-image-no" //if answer was no and image is next
when
	state: GUI_state(currentQuestion=="Are you paying in change?",ans == "No")
	ui: GUI()
then
	System.out.println("corona");
	state.setImg("src/main/resources/grafiki/coronaextra.png");
	ui.closeGUI(state.getImg());
end

rule "french-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Can you speak fluent French, in Russian?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Are you having a dinner party?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "french-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Can you speak fluent French, in Russian?",ans == "Yes")
	ui: GUI()
then
	System.out.println("dosequis");
	state.setImg("src/main/resources/grafiki/cervezadosequis.png");
	ui.closeGUI(state.getImg());
end

rule "dinner-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Are you having a dinner party?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Did you just graduate college?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "dinner-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Are you having a dinner party?",ans == "Yes")
	ui: GUI()
then
	System.out.println("blue samuel belgium gordon");
	state.setImg("src/main/resources/grafiki/bluemoon.png;src/main/resources/grafiki/samueladams.png;src/main/resources/grafiki/newbelgiumbrewing.png;src/main/resources/grafiki/gordonbiersch.png");
	ui.closeGUI(state.getImg());
end

rule "graduate-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Did you just graduate college?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Are you a Parrothead?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "graduate-yes" //if answer was yes and question is next
when
	state: GUI_state(currentQuestion=="Did you just graduate college?", ans=="Yes");
	ui: GUI();
then
	Question q = new Question("...but did you move back in with your parents?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "parents-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="...but did you move back in with your parents?",ans == "Yes")
	ui: GUI()
then
	System.out.println("mickeys milwaukee olde");
	state.setImg("src/main/resources/grafiki/mickeys.png;src/main/resources/grafiki/oldmilwaukee.png;src/main/resources/grafiki/oldeenglish800.png");
	ui.closeGUI(state.getImg());
end

rule "parents-image-no" //if answer was no and image is next
when
	state: GUI_state(currentQuestion=="...but did you move back in with your parents?",ans == "No")
	ui: GUI()
then
	System.out.println("rolling becks heineken");
	state.setImg("src/main/resources/grafiki/rollingrockextrapale.png;src/main/resources/grafiki/becks.png;src/main/resources/grafiki/heineken.png");
	ui.closeGUI(state.getImg());
end

rule "parrothead-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Are you a Parrothead?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Are you trying to seem \"wordly\"?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "parrothead-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Are you a Parrothead?",ans == "Yes")
	ui: GUI()
then
	System.out.println("landshark");
	state.setImg("src/main/resources/grafiki/landshark.png");
	ui.closeGUI(state.getImg());
end

rule "worldly-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Are you trying to seem \"wordly\"?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Did you bring in a reusable grocery bag?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "worldly-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Are you trying to seem \"wordly\"?",ans == "Yes")
	ui: GUI()
then
	System.out.println("fosters redstripe carlsberg");
	state.setImg("src/main/resources/grafiki/fosters.png;src/main/resources/grafiki/redstripe.png;src/main/resources/grafiki/carlsberg.png");
	ui.closeGUI(state.getImg());
end

rule "bag-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Did you bring in a reusable grocery bag?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Are you drunk?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "bag-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Did you bring in a reusable grocery bag?",ans == "Yes")
	ui: GUI()
then
	System.out.println("hook sierra harp newcastle stella");
	state.setImg("src/main/resources/grafiki/redhook.png;src/main/resources/grafiki/sierranevada.png;src/main/resources/grafiki/harplager.png;src/main/resources/grafiki/newcastlebrownale.png;src/main/resources/grafiki/stellaartois.png");
	ui.closeGUI(state.getImg());
end

rule "drunk-no" //if answer was no and question is next
when
	state: GUI_state(currentQuestion=="Are you drunk?", ans=="No");
	ui: GUI();
then
	Question q = new Question("Do you truly *love* beer?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "drunk-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="Are you drunk?",ans == "Yes")
	ui: GUI()
then
	System.out.println("tecate moosehead");
	state.setImg("src/main/resources/grafiki/cervezatecate.png;src/main/resources/grafiki/mooseheadlager.png");
	ui.closeGUI(state.getImg());
end

rule "love-image-no" //if answer was no and image is next
when
	state: GUI_state(currentQuestion=="Do you truly *love* beer?",ans == "No")
	ui: GUI()
then
	System.out.println("michelob bass");
	state.setImg("src/main/resources/grafiki/michelobultra.png;src/main/resources/grafiki/bass.png");
	ui.closeGUI(state.getImg());
end

rule "love-yes" //if answer was yes and question is next
when
	state: GUI_state(currentQuestion=="Do you truly *love* beer?", ans=="Yes");
	ui: GUI();
then
	Question q = new Question("...$500 love?","Yes;No");
	insert(q);
	state.setCurrentQuestion(q.getQuest());
	state.setPossible(q.getAnswers());
	ui.updateGUI(state.getCurrentQuestion(),state.getPossible());
end

rule "love500-image-yes" //if answer was yes and image is next
when
	state: GUI_state(currentQuestion=="...$500 love?",ans == "Yes")
	ui: GUI()
then
	System.out.println("weird bottle");
	state.setImg("src/main/resources/grafiki/wtf.png");
	ui.closeGUI(state.getImg());
end

rule "love500-image-no" //if answer was no and image is next
when
	state: GUI_state(currentQuestion=="...$500 love?",ans == "No")
	ui: GUI()
then
	System.out.println("alaskan ale dogfish double cantillon stone full hair clipper");
	state.setImg("src/main/resources/grafiki/alaskanamber.png;src/main/resources/grafiki/aleasylum.png;src/main/resources/grafiki/dogfishcraftbrewedales.png;src/main/resources/grafiki/doublediamond.png;src/main/resources/grafiki/cantillon.png;src/main/resources/grafiki/stonebrewingco.png;src/main/resources/grafiki/fullsail.png;src/main/resources/grafiki/hairdog.png;src/main/resources/grafiki/clippercity.png");
	ui.closeGUI(state.getImg());
end
rule "Retrieve answer" //at the end of drl file
when
	state : GUI_state()
	answer : String()
	q: Question(quest == state.getCurrentQuestion())
then
System.out.println(state.getCurrentQuestion());
	state.setAns(answer);
	//q.setAns(answer);
	update(state);
	//update(q);
	retract(answer);
	System.out.println(state.getAns());
	
end
